version: 2

jobs:
  build:
    docker:
      - image: ruby:2.3
    steps:
      - checkout
      - run:
          name: Installing Gems
          command: bundle install
      - run:
          name: Executing tests
          command: bundle exec rspec
